[package]
name = "anyhow-std"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
derive-new = "0.5.9"
derive_more = "0.99.17"

[dev-dependencies]
tempfile = "3.5.0"
test-case = "3.0.0"
